name: flutter_game_of_flags
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  page_transition: ^2.2.1
  confetti: ^0.8.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#5DA8D4"
  image: "assets/icon.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#5DA8D4"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/